baseurl = "https://ian-liz.com"
title = "Ian & Liz's Wedding"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableRSS = true

[params]
  title = "April 14, 2018"
  description = "Ian & Liz's Wedding"

  logo = "fa-diamond"
  copyright = "2017"

